SELECT M.ID_MODELO, M.DESCRICAO, SUM(I.QUANTIDADE) QUANTIDADE
  FROM VENDA  V
  JOIN ITEM	  I ON V.ID_VENDA  = I.ID_VENDA
  JOIN MODELO M ON I.ID_MODELO = M.ID_MODELO
 WHERE M.ID_MODELO = 1
 GROUP BY M.ID_MODELO, M.DESCRICAO;