SELECT C.ID_CLIENTE, C.NOME, C.CPF, MAX(V.DATA_VENDA) DATA_VENDA
  FROM VENDA   V
  JOIN ITEM    I ON V.ID_VENDA   = I.ID_VENDA
  JOIN CLIENTE C ON V.ID_CLIENTE = C.ID_CLIENTE
  JOIN MODELO  M ON I.ID_MODELO  = M.ID_MODELO
 WHERE C.CPF LIKE '0%'
   AND YEAR(M.LANCAMENTO) >= 2010
   AND (SELECT COUNT(1)
		  FROM VENDA V1
		  JOIN ITEM I1 ON V1.ID_VENDA = I1.ID_VENDA
		 WHERE I1.ID_MODELO = 1 
		   AND V1.ID_CLIENTE   = C.ID_CLIENTE) < 2
 GROUP BY C.ID_CLIENTE, C.NOME, C.CPF
 ORDER BY MAX(V.DATA_VENDA) DESC
 LIMIT 15;